import type { GetServerSideProps } from "next";
import prisma from "../lib/prisma";
import Head from "next/head";
import { Brand, Category, Location } from "@prisma/client";
import ItemTable from "../components/ItemTable";

export type IServerItem = {
  id: number;
  price: number;
  working: boolean;
  Item: IServerItemDetails;
  Brand: Brand;
  Location: Location;
};

export type IServerItemDetails = {
  name: string;
  Category: Category;
};

const Home = ({ items }: { items: IServerItem[] }) => {
  console.log(items);

  return (
    <div>
      <Head>
        <title>Inventory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <h2>Inventory</h2>
        <ItemTable items={items} />
      </>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const items = await prisma.itemInfo.findMany({
    select: {
      id: true,
      price: true,
      working: true,
      Brand: true,
      Comment: true,
      Location: true,
      Item: {
        select: {
          name: true,
          Category: true,
        },
      },
    },
  });
  return {
    props: {
      items,
    },
  };
};

export default Home;
